### ISSUE TITLE
Orientacion primeros pasos con el IDE Visual Studio

### ISSUE THREAD

**Issue by crez607** [MicrosoftDocs/cpp-docs.es-es#39]
Muy claro, conciso, y muy facil de entender estos primeros pasos en el uso del Programa.  Asi como las explicaciones, paso a paso, para quienes como yo, estamos iniciandonos en C++ y el uso del IDE.
Gracias.

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: f51e5807-3f78-ff63-ef41-4629b7ae84d5
* Version Independent ID: c1dbef6c-f895-a6d7-9d83-e2ac8f864327
* Content: [Creación de un proyecto de aplicación de consola de C++](https://docs.microsoft.com/es-es/cpp/get-started/tutorial-console-cpp?view=vs-2019#feedback)
* Content Source: [docs/get-started/tutorial-console-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.es-es/blob/live/docs/get-started/tutorial-console-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @crez607
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hola, @crez607:

Apreciamos enormemente sus comentarios. Nos complace comprobar que su experiencia con la documentación cumple con sus expectativas.  

Le recomendamos que proporcione comentarios para que podamos seguir mejorando su experiencia.  

Atentamente,  
Equipo internacional de Microsoft Docs
