### ISSUE TITLE
Codigo C++ dentro de Visual Studio para programas no en Consola Windows.

### ISSUE THREAD

**Issue by crez607** [MicrosoftDocs/cpp-docs.es-es#40]
Saludos a la comunidad.
¿ Hay algún ejemplo de código en C++ para principiantes, que incluya un cuadro en la interfase gráfica de Windows en lugar de hacer el tradicional ejemplo de ¡Hola Mundo! solo para salida en consola ?
¿ Es muy complicado escribir el código en el IDE de Visual Studio para diseñar una ventana estilo Windows, mas llamativa que la consola ?

**Comment by srvbpigh** [comment]
Hello, @crez607
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by crez607** [comment]
Thank you.

**Comment by ticianaciminari** [comment]
Hola, @crez607:

Agradecemos enormemente su colaboración. Nuestro equipo solo puede responder a comentarios relacionados con la documentación.  

Registre los comentarios de su producto mediante el botón "Comentarios sobre el producto" en la parte inferior de la página de DOCS.  

Si tiene comentarios relacionados con la documentación, regístrelos a través de este canal.  

Apreciamos su contribución a nuestros artículos.   

Atentamente,  

Equipo internacional de Microsoft Docs
