### ISSUE TITLE
Me ha sido útil, he podido configurar VS2019 para procesar C++17 

### ISSUE THREAD

**Issue by anxonpues** [MicrosoftDocs/cpp-docs.es-es#42]
Maybe it's me who started to use more help in a different way to enter or that if ask with the mistakes that I received like Cxxxx and then navigate to refferences wich appeared thereafter...
Thanks

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 6183aaac-1eb4-f704-4bf5-1c3fe67ae2fe
* Version Independent ID: d3f24754-fcba-3eee-e34d-445962c5485c
* Content: [/std (Especificar la versión estándar del lenguaje)](https://docs.microsoft.com/es-es/cpp/build/reference/std-specify-language-standard-version?view=vs-2019#feedback)
* Content Source: [docs/build/reference/std-specify-language-standard-version.md](https://github.com/MicrosoftDocs/cpp-docs.es-es/blob/live/docs/build/reference/std-specify-language-standard-version.md)
* Product: **visual-cpp**
* Technology: **cpp-tools**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @anxonpues
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @anxonpues 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
